// Lightweight metadata only — used by server components (generateMetadata, generateStaticParams).
// Does NOT include sections/content to avoid large-bundle webpack chunk conflicts.
// Full data (with sections) lives in lib/blogData.js and is imported only by client components.

export const blogMeta = [
  {
    slug: "jasa-pembuatan-website-malang",
    title: "Jasa Pembuatan Website Malang: Panduan Lengkap Memilih Agency Digital Terbaik",
    metaTitle: "Jasa Pembuatan Website Malang Profesional | Cherrypick Studio",
    metaDescription:
      "Cari jasa pembuatan website profesional di Malang? Cherrypick Studio mengembangkan website bisnis, toko online, dan aplikasi web modern dengan teknologi terkini. Konsultasi gratis!",
    publishedAt: "2025-01-10",
    updatedAt: "2025-03-01",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/jasa-pembuatan-website-malang-cover.svg",
    coverImageAlt: "Jasa Pembuatan Website Malang - Cherrypick Studio",
    primaryKeyword: "jasa pembuatan website Malang",
    secondaryKeywords: ["web developer Malang", "harga pembuatan website", "website bisnis Indonesia", "agency digital Malang"],
    category: "Web Development",
    targetMarket: "ID",
  },
  {
    slug: "web-development-agency-singapore",
    title: "Web Development Agency Singapore: Building Digital Products That Scale",
    metaTitle: "Web Development Agency Singapore | Cherrypick Studio",
    metaDescription:
      "Looking for a reliable web development agency in Singapore? Cherrypick Studio builds scalable web apps, mobile apps, and digital products for Singapore businesses. Get a free consultation.",
    publishedAt: "2025-01-20",
    updatedAt: "2025-03-05",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/web-development-agency-singapore-cover.svg",
    coverImageAlt: "Web Development Agency Singapore - Cherrypick Studio",
    primaryKeyword: "web development agency Singapore",
    secondaryKeywords: ["Singapore web developer", "digital product agency Singapore", "React developer Singapore", "web app development Singapore"],
    category: "Web Development",
    targetMarket: "SG",
  },
  {
    slug: "ui-ux-design-process-explained",
    title: "UI/UX Design Process Explained: From Research to Handoff",
    metaTitle: "UI/UX Design Process Explained — A Complete Guide | Cherrypick Studio",
    metaDescription:
      "Understand the full UI/UX design process — from user research and wireframing to prototyping and developer handoff. Learn how professional design agencies approach product design.",
    publishedAt: "2025-02-03",
    updatedAt: "2025-03-10",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/ui-ux-design-process-explained-cover.svg",
    coverImageAlt: "UI/UX Design Process - Cherrypick Studio",
    primaryKeyword: "UI/UX design process",
    secondaryKeywords: ["UX design steps", "design thinking process", "user-centred design", "product design process"],
    category: "UI/UX",
    targetMarket: "Both",
  },
  {
    slug: "perbedaan-web-app-dan-mobile-app",
    title: "Perbedaan Web App dan Mobile App: Mana yang Tepat untuk Bisnis Anda?",
    metaTitle: "Perbedaan Web App dan Mobile App | Panduan Lengkap 2025",
    metaDescription:
      "Bingung memilih antara web app dan mobile app untuk bisnis Anda? Pelajari perbedaan, kelebihan, kekurangan, dan kapan harus memilih masing-masing solusi dalam panduan lengkap ini.",
    publishedAt: "2025-02-15",
    updatedAt: "2025-03-08",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/perbedaan-web-app-dan-mobile-app-cover.svg",
    coverImageAlt: "Perbedaan Web App dan Mobile App",
    primaryKeyword: "perbedaan web app dan mobile app",
    secondaryKeywords: ["web app vs mobile app", "aplikasi web atau mobile", "jasa pengembangan aplikasi", "biaya buat aplikasi"],
    category: "Mobile",
    targetMarket: "ID",
  },
  {
    slug: "what-is-brand-identity-and-why-it-matters",
    title: "What Is Brand Identity and Why It Matters for Digital Businesses",
    metaTitle: "What Is Brand Identity? Why It Matters for Digital Business | Cherrypick Studio",
    metaDescription:
      "Discover what brand identity really means for digital businesses — beyond just a logo. Learn the core elements, why it drives business growth, and how to build a brand that resonates.",
    publishedAt: "2025-02-28",
    updatedAt: "2025-03-12",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/what-is-brand-identity-and-why-it-matters-cover.svg",
    coverImageAlt: "Brand Identity for Digital Business - Cherrypick Studio",
    primaryKeyword: "brand identity for digital business",
    secondaryKeywords: ["what is brand identity", "brand design agency", "visual identity design", "brand strategy"],
    category: "Branding",
    targetMarket: "Both",
  },
  {
    slug: "transformasi-digital-umkm-indonesia",
    title: "Transformasi Digital UMKM Indonesia: Panduan Praktis Memulai di 2025",
    metaTitle: "Transformasi Digital UMKM Indonesia 2025 | Panduan Praktis",
    metaDescription:
      "Panduan lengkap transformasi digital untuk UMKM Indonesia: apa itu, mengapa penting, dan langkah konkret yang bisa dimulai sekarang untuk meningkatkan daya saing bisnis Anda.",
    publishedAt: "2025-03-01",
    updatedAt: "2025-03-14",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/transformasi-digital-umkm-indonesia-cover.svg",
    coverImageAlt: "Transformasi Digital UMKM Indonesia",
    primaryKeyword: "transformasi digital UMKM Indonesia",
    secondaryKeywords: ["digitalisasi UMKM", "teknologi untuk UMKM", "bisnis digital Indonesia", "go digital UMKM"],
    category: "Digital Transformation",
    targetMarket: "ID",
  },
  {
    slug: "saas-dashboard-design-best-practices",
    title: "SaaS Dashboard Design Best Practices: Building Interfaces That Drive Action",
    metaTitle: "SaaS Dashboard Design Best Practices 2025 | Cherrypick Studio",
    metaDescription:
      "Learn the essential best practices for designing SaaS dashboards that users actually understand and act on — from data hierarchy and visualisation to navigation and performance.",
    publishedAt: "2025-01-25",
    updatedAt: "2025-03-06",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/saas-dashboard-design-best-practices-cover.svg",
    coverImageAlt: "SaaS Dashboard Design Best Practices",
    primaryKeyword: "SaaS dashboard design best practices",
    secondaryKeywords: ["dashboard UI design", "data visualisation design", "SaaS UX design", "analytics dashboard design"],
    category: "UI/UX",
    targetMarket: "SG",
  },
  {
    slug: "cara-memilih-tech-stack-untuk-startup",
    title: "Cara Memilih Tech Stack untuk Startup: Panduan dari Para Engineer",
    metaTitle: "Cara Memilih Tech Stack untuk Startup Indonesia | Panduan 2025",
    metaDescription:
      "Bingung memilih tech stack untuk startup Anda? Panduan lengkap ini membahas faktor penting dalam pemilihan tech stack, opsi populer, dan rekomendasi berdasarkan tahap bisnis Anda.",
    publishedAt: "2025-02-10",
    updatedAt: "2025-03-09",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/cara-memilih-tech-stack-untuk-startup-cover.svg",
    coverImageAlt: "Cara Memilih Tech Stack untuk Startup",
    primaryKeyword: "cara memilih tech stack startup",
    secondaryKeywords: ["tech stack terbaik startup", "React vs Vue", "Node.js vs Laravel", "teknologi startup Indonesia"],
    category: "Web Development",
    targetMarket: "ID",
  },
  {
    slug: "e-commerce-platform-development-indonesia",
    title: "E-Commerce Platform Development in Indonesia: Build vs Buy vs Customise",
    metaTitle: "E-Commerce Platform Development Indonesia | Build vs Buy Guide",
    metaDescription:
      "Should you build a custom e-commerce platform or use an existing solution? This guide covers key considerations, architecture decisions, and payment integrations for Indonesia's market.",
    publishedAt: "2025-02-20",
    updatedAt: "2025-03-11",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/e-commerce-platform-development-indonesia-cover.svg",
    coverImageAlt: "E-Commerce Platform Development Indonesia",
    primaryKeyword: "e-commerce platform development Indonesia",
    secondaryKeywords: ["build e-commerce Indonesia", "custom online store development", "Indonesia payment gateway", "e-commerce web development"],
    category: "Web Development",
    targetMarket: "Both",
  },
  {
    slug: "how-to-brief-a-design-agency",
    title: "How to Brief a Design Agency: A Complete Guide to Getting Great Results",
    metaTitle: "How to Brief a Design Agency: Get Better Results | Cherrypick Studio",
    metaDescription:
      "Learn how to write a design brief that gets you better results from your design agency. Covers goals, audience, brand guidelines, timeline, and the most common mistakes to avoid.",
    publishedAt: "2025-03-05",
    updatedAt: "2025-03-14",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/how-to-brief-a-design-agency-cover.svg",
    coverImageAlt: "How to Brief a Design Agency",
    primaryKeyword: "how to brief a design agency",
    secondaryKeywords: ["design brief template", "creative brief", "agency brief", "project brief"],
    category: "Design Process",
    targetMarket: "Both",
  },
  {
    slug: "ai-tools-for-saas-founders",
    title: "AI Tools for SaaS Founders: What's Actually Worth Using in 2025",
    metaTitle: "Best AI Tools for SaaS Founders in 2025 | Cherrypick Studio",
    metaDescription:
      "A practical guide to AI tools that SaaS founders are actually using — from product development and customer research to marketing automation and code generation. Cut through the hype.",
    publishedAt: "2025-03-10",
    updatedAt: "2025-03-15",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/ai-tools-for-saas-founders-cover.svg",
    coverImageAlt: "AI Tools for SaaS Founders 2025",
    primaryKeyword: "AI tools for SaaS founders",
    secondaryKeywords: ["best AI tools 2025", "AI for startups", "SaaS productivity tools", "AI product development"],
    category: "AI & SaaS",
    targetMarket: "Both",
  },
  {
    slug: "vibe-coding-what-it-means-for-software-development",
    title: "Vibe Coding: What It Means for Software Development and When It Makes Sense",
    metaTitle: "Vibe Coding Explained: Opportunities and Risks for Developers | Cherrypick Studio",
    metaDescription:
      "Vibe coding — building software by prompting AI rather than writing code — is reshaping how products get built. Here's an honest look at what it enables, where it breaks down, and what it means for your team.",
    publishedAt: "2025-03-12",
    updatedAt: "2025-03-15",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/vibe-coding-what-it-means-for-software-development-cover.svg",
    coverImageAlt: "Vibe Coding and AI-Assisted Development",
    primaryKeyword: "vibe coding software development",
    secondaryKeywords: ["AI coding assistant", "AI pair programmer", "build software with AI", "prompt-driven development"],
    category: "AI & Development",
    targetMarket: "Both",
  },
  {
    slug: "how-to-validate-your-saas-idea-before-building",
    title: "How to Validate Your SaaS Idea Before Building: A Founder's Playbook",
    metaTitle: "How to Validate a SaaS Idea Before Building | Founder's Playbook",
    metaDescription:
      "Build the right thing before you build anything. A practical playbook for SaaS founders on validating product-market fit, from problem interviews to pre-sell experiments, before writing a line of code.",
    publishedAt: "2025-03-08",
    updatedAt: "2025-03-14",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/how-to-validate-your-saas-idea-before-building-cover.svg",
    coverImageAlt: "How to Validate a SaaS Idea Before Building",
    primaryKeyword: "how to validate SaaS idea",
    secondaryKeywords: ["SaaS product validation", "validate startup idea", "pre-sell SaaS", "product-market fit"],
    category: "SaaS Founders",
    targetMarket: "Both",
  },
  {
    slug: "building-saas-product-with-ai-in-2025",
    title: "Building a SaaS Product with AI in 2025: Lessons from the Trenches",
    metaTitle: "Building a SaaS Product with AI in 2025 | Lessons & Best Practices",
    metaDescription:
      "What does it actually look like to build a SaaS product with AI tools in 2025? We share lessons from real product builds — what accelerated, what backfired, and what the workflow looks like end to end.",
    publishedAt: "2025-03-13",
    updatedAt: "2025-03-15",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/building-saas-product-with-ai-in-2025-cover.svg",
    coverImageAlt: "Building a SaaS Product with AI in 2025",
    primaryKeyword: "building SaaS product with AI 2025",
    secondaryKeywords: ["AI product development", "SaaS development 2025", "AI-assisted coding", "build startup with AI"],
    category: "AI & SaaS",
    targetMarket: "Both",
  },
  {
    slug: "saas-pricing-strategy-for-founders",
    title: "SaaS Pricing Strategy for Founders: How to Price Your Product Without Leaving Money on the Table",
    metaTitle: "SaaS Pricing Strategy for Founders: The Complete Guide | Cherrypick Studio",
    metaDescription:
      "Pricing is your most powerful growth lever and the most under-optimised part of most SaaS products. A founder's guide to SaaS pricing models, psychology, and experiments that move revenue.",
    publishedAt: "2025-03-06",
    updatedAt: "2025-03-14",
    author: "Cherrypick Studio",
    coverImage: "/images/blog/saas-pricing-strategy-for-founders-cover.svg",
    coverImageAlt: "SaaS Pricing Strategy for Founders",
    primaryKeyword: "SaaS pricing strategy founders",
    secondaryKeywords: ["how to price SaaS product", "SaaS pricing models", "value-based pricing", "SaaS revenue growth"],
    category: "SaaS Founders",
    targetMarket: "Both",
  },
];

export function getBlogMeta(slug) {
  return blogMeta.find((p) => p.slug === slug) ?? null;
}

export function getAllSlugs() {
  return blogMeta.map((p) => p.slug);
}
